feat(server): allow named url shortening (#40)
orhun/rustypaste pull request #373
Opened 2024-12-05 22:46 UTC by Vaelatern

## Description

I ran the filename header through the URL shortening route

## Motivation and Context

This lets me use rustypaste to link to a specific link using a specified short name (for ergonomics).

Also fixes #40 by the by.

## How Has This Been Tested?

## Changelog Entry

```
### Added

- Enable naming shortened URLs beyond using a random string or the text "url"
````
-->

## Types of Changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [ ] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-12-05 22:57 UTC, tessus commented
Thanks for the PR. Can you also please add test cases and fixtures?

2024-12-05 23:08 UTC, tessus commented
There are a few things to fix. The formatting checks, lints, and tests fail. These have to be fixed and new tests should be added that handle your use case.

2024-12-05 23:38 UTC, tessus requested changes
Unfortunately there are still issues with this PR.

May I suggest to go through the checklist?

- `cargo fmt --check --`
- `cargo clippy`
- `cargo test -- --test-threads 1`
- `./fixtures/test-fixtures.sh`

Currently the code does not even compile.

2024-12-06 01:00 UTC, Vaelatern commented
I've pushed an update now, it passes CI on my own fork.

2024-12-06 01:38 UTC, tessus approved these changes
Nice, this looks good. Thanks.

2024-12-06 01:41 UTC, tessus commented
@orhun can you please have a look? I promised I would only merge dependency PRs. ;-)

@Vaelatern let's wait for orhun's approval, since he's the owner of the project. I can't merge without his ok.

2024-12-06 01:43 UTC, Vaelatern commented
Sounds good!

I just started using this today, noticed this hole, and wanted to contribute a fix.

2024-12-06 01:56 UTC, Vaelatern commented
Apparently I need to sign the commits too

2024-12-06 01:57 UTC, tessus commented
why? nope, you don't. This project does not have a requirement of signed commits.

2024-12-06 02:00 UTC, tessus commented
oops, yeah. I am sorry. this policy must be new.

2024-12-06 02:03 UTC, Vaelatern commented
Now pushed with signed commit, both this and #374  (which I'm about to refactor a tiny bit)

2024-12-06 02:04 UTC, tessus commented
Thanks.

2024-12-07 15:05 UTC, orhun approved these changes
Good stuff 💯 

Thanks!

2024-12-07 15:05 UTC, merged